apiVersion: v1
kind: Pod
metadata:
  name: centos-edge21
spec:
  containers:
  - command:
    - sh
    - -c
    - while true; do sleep 3600; done
    image: centos:centos8
    name: centos
    securityContext:
      privileged: true
  nodeName: edge2
  restartPolicy: Always
