apiVersion: cnf.namla.com/v1alpha1
kind: CloudNativeNetworkFunction
metadata:
  name: cnf-wan-mpls-1-edge2
  namespace: namla-system
spec:
  address: 10.25.13.109/24
  ifname: ens6
  nodename: edge2
  nvni-name: nvni-3
  type: WAN
  control-plane:
    bgp-as: 64513
---
apiVersion: cnf.namla.com/v1alpha1
kind: CloudNativeNetworkLinuxRoute
metadata:
  name: cnf-route-cnf-wan-mpls-1-edge2-2
  namespace: namla-system
spec:
  nodename: edge2
  cnf: cnf-wan-mpls-1-edge2
  config:
    scope: GLOBAL
    dst_network: 10.25.2.0/24
    gw_addr: 10.25.13.25 # --> 142
    metric: 0
---
apiVersion: cnf.namla.com/v1alpha1
kind: CloudNativeNetworkLinuxRoute
metadata:
  name: cnf-route-cnf-wan-mpls-1-edge2-10
  namespace: namla-system
spec:
  nodename: edge2
  cnf: cnf-wan-mpls-1-edge2
  config:
    scope: GLOBAL
    dst_network: 10.25.10.0/24
    gw_addr: 10.25.13.25 # --> 142
    metric: 0
