apiVersion: cnf.namla.com/v1alpha1
kind: CloudNativeNetworkFunction
metadata:
  name: cnf-wan-mpls-1-edge4
  namespace: namla-system
spec:
  address: 192.168.18.245/24
  ifname: enp2s0
  nodename: edge4
  transport_network: mpls
  nvni-name: nvni-1
  type: WAN
  control-plane:
    bgp-as: 64513
---
apiVersion: cnf.namla.com/v1alpha1
kind: CloudNativeNetworkLinuxRoute
metadata:
  name: cnf-route-cnf-wan-mpls-1-edge4-1
  namespace: namla-system
spec:
  nodename: edge4
  cnf: cnf-wan-mpls-1-edge4
  config:
    scope: GLOBAL
    dst_network: 192.168.18.235/32
    gw_addr: 192.168.18.1  # ---> 77
    metric: 0
---
apiVersion: cnf.namla.com/v1alpha1
kind: CloudNativeNetworkLinuxRoute
metadata:
  name: cnf-route-cnf-wan-mpls-1-edge4-2
  namespace: namla-system
spec:
  nodename: edge4
  cnf: cnf-wan-mpls-1-edge4
  config:
    scope: GLOBAL
    dst_network: 192.168.18.170/32
    gw_addr: 192.168.18.1  # ---> 77
    metric: 0
---
apiVersion: cnf.namla.com/v1alpha1
kind: CloudNativeNetworkLinuxRoute
metadata:
  name: cnf-route-cnf-wan-mpls-1-edge4-3
  namespace: namla-system
spec:
  nodename: edge4
  cnf: cnf-wan-mpls-1-edge4
  config:
    scope: GLOBAL
    dst_network: 192.168.18.186/32
    gw_addr: 192.168.18.1  # ---> 77
    metric: 0


