apiVersion: cnf.namla.com/v1alpha1
kind: CloudNativeNetworkFunction
metadata:
  name: cnf-wan-mpls-1-edge3
  namespace: namla-system
spec:
  address: 192.168.18.136/24
  ifname: enp3s0
  nodename: edge3
  nvni-name: nvni-2
  transport_network: mpls
  type: WAN
  control-plane:
    bgp-as: 64513
---
apiVersion: cnf.namla.com/v1alpha1
kind: CloudNativeNetworkLinuxRoute
metadata:
  name: cnf-route-cnf-wan-mpls-1-edge3-1
  namespace: namla-system
spec:
  nodename: edge3
  cnf: cnf-wan-mpls-1-edge3
  config:
    scope: GLOBAL
    dst_network: 192.168.18.223/32
    gw_addr: 192.168.18.1  # ---> 77
    metric: 0
---
apiVersion: cnf.namla.com/v1alpha1
kind: CloudNativeNetworkLinuxRoute
metadata:
  name: cnf-route-cnf-wan-mpls-1-edge3-2
  namespace: namla-system
spec:
  nodename: edge3
  cnf: cnf-wan-mpls-1-edge3
  config:
    scope: GLOBAL
    dst_network: 192.168.18.192/32
    gw_addr: 192.168.18.1  # ---> 77
    metric: 0
---
apiVersion: cnf.namla.com/v1alpha1
kind: CloudNativeNetworkLinuxRoute
metadata:
  name: cnf-route-cnf-wan-mpls-1-edge3-4
  namespace: namla-system
spec:
  nodename: edge3
  cnf: cnf-wan-mpls-1-edge3
  config:
    scope: GLOBAL
    dst_network: 192.168.18.168/32
    gw_addr: 192.168.18.1  # ---> 77
    metric: 0

