apiVersion: cnf.namla.com/v1alpha1
kind: CloudNativeNetworkControllerVpnProfile
metadata:
  name: cnf-vpn-profile-cnf-lan-lan-2-edge3
  namespace: namla-system
spec:
  nodename: edge3
  cnf: cnf-lan-lan-2-edge3
  config:
    controllerId:
      id: controllercnf@namla.cloud
      type: RFC822_ADDR
    controllerIpAddress: 20.126.152.166
    transportNetwork: internet
    mgmtType: SINGLE
    localId:
      id: lan-edge3@namla.cloud
      type: RFC822_ADDR
    authentication:
      type: psk
      name: controller1-cnf
      key: password
    outGoingCnfs: 
    - cnf-wan-internet-1-edge3
    - cnf-wan-mpls-1-edge3