apiVersion: cnf.namla.com/v1alpha1
kind: CloudNativeNetworkControllerVpnProfile
metadata:
  name: cnf-vpn-profile-cnf-lan-lan-2-edge4
  namespace: namla-system
spec:
  nodename: edge4
  cnf: cnf-lan-lan-2-edge4
  config:
    controllerId:
      id: controllercnf@namla.cloud
      type: RFC822_ADDR
    controllerIpAddress: 34.38.169.198
    transportNetwork: internet
    mgmtType: SINGLE
    localId:
      id: lan-edge4@namla.cloud
      type: RFC822_ADDR
    authentication:
      type: psk
      name: controller1-cnf
      key: password
    outGoingCnfs: 
    - cnf-wan-internet-1-edge4
    - cnf-wan-mpls-1-edge4