---
apiVersion: cnf.namla.com/v1alpha1
kind: CloudNativeNetworkFunction
metadata:
  name: cnf-wan-mpls-1-edge1
  namespace: namla-system
spec:
  address: 10.25.10.111/24
  ifname: ens5
  nodename: edge1
  nvni-name: nvni-2
  type: WAN
  control-plane:
    bgp-as: 64513
---
apiVersion: cnf.namla.com/v1alpha1
kind: CloudNativeNetworkLinuxRoute
metadata:
  name: cnf-route-cnf-wan-mpls-1-edge1-2
  namespace: namla-system
spec:
  nodename: edge1
  cnf: cnf-wan-mpls-1-edge1
  config:
    scope: GLOBAL
    dst_network: 10.25.2.0/24
    gw_addr: 10.25.10.37  # ---> 77
    metric: 0
---
apiVersion: cnf.namla.com/v1alpha1
kind: CloudNativeNetworkLinuxRoute
metadata:
  name: cnf-route-cnf-wan-mpls-1-edge1-13
  namespace: namla-system
spec:
  nodename: edge1
  cnf: cnf-wan-mpls-1-edge1
  config:
    scope: GLOBAL
    dst_network: 10.25.13.0/24
    gw_addr: 10.25.10.37  # ---> 77
    metric: 0
