apiVersion: cnf.namla.com/v1alpha1
kind: CloudNativeNetworkFunction
metadata:
  name: cnf-wan-mpls-1-edge5
  namespace: namla-system
spec:
  address: 192.168.18.149/24
  ifname: enp10s0
  nodename: edge5
  nvni-name: nvni-2
  transport_network: mpls
  type: WAN
  control-plane:
    bgp-as: 64513
---
apiVersion: cnf.namla.com/v1alpha1
kind: CloudNativeNetworkLinuxRoute
metadata:
  name: cnf-route-cnf-wan-mpls-1-edge5-3
  namespace: namla-system
spec:
  nodename: edge5
  cnf: cnf-wan-mpls-1-edge5
  config:
    scope: GLOBAL
    dst_network: 192.168.18.182/32
    gw_addr: 192.168.18.1  # ---> 77
    metric: 0
---
apiVersion: cnf.namla.com/v1alpha1
kind: CloudNativeNetworkLinuxRoute
metadata:
  name: cnf-route-cnf-wan-mpls-1-edge5-4
  namespace: namla-system
spec:
  nodename: edge5
  cnf: cnf-wan-mpls-1-edge5
  config:
    scope: GLOBAL
    dst_network: 192.168.18.178/32
    gw_addr: 192.168.18.1  # ---> 77
    metric: 0