---
apiVersion: cnf.namla.com/v1alpha1
kind: CloudNativeNetworkFunction
metadata:
  name: cnf-wan-mpls-1-edge1
  namespace: namla-system
spec:
  address: 192.168.18.235/24
  ifname: enp9s0
  nodename: edge1
  nvni-name: nvni-2
  transport_network: mpls
  type: WAN
  control-plane:
    bgp-as: 64513
---
apiVersion: cnf.namla.com/v1alpha1
kind: CloudNativeNetworkLinuxRoute
metadata:
  name: cnf-route-cnf-wan-mpls-1-edge1-2
  namespace: namla-system
spec:
  nodename: edge1
  cnf: cnf-wan-mpls-1-edge1
  config:
    scope: GLOBAL
    dst_network: 192.168.18.170/32
    gw_addr: 192.168.18.1  # ---> 77
    metric: 0
---
apiVersion: cnf.namla.com/v1alpha1
kind: CloudNativeNetworkLinuxRoute
metadata:
  name: cnf-route-cnf-wan-mpls-1-edge1-3
  namespace: namla-system
spec:
  nodename: edge1
  cnf: cnf-wan-mpls-1-edge1
  config:
    scope: GLOBAL
    dst_network: 192.168.18.186/32
    gw_addr: 192.168.18.1  # ---> 77
    metric: 0
---
apiVersion: cnf.namla.com/v1alpha1
kind: CloudNativeNetworkLinuxRoute
metadata:
  name: cnf-route-cnf-wan-mpls-1-edge1-4
  namespace: namla-system
spec:
  nodename: edge1
  cnf: cnf-wan-mpls-1-edge1
  config:
    scope: GLOBAL
    dst_network: 192.168.18.245
    gw_addr: 192.168.18.1  # ---> 77
    metric: 0