apiVersion: cnf.namla.com/v1alpha1
kind: CloudNativeNetworkFunction
metadata:
  name: cnf-wan-internet-1-edge4
  namespace: namla-system
spec:
  address: 192.168.30.157/24
  ifname: enp6s0
  nodename: edge4
  transport_network: internet
  nvni-name: nvni-1
  type: WAN
  control-plane:
    bgp-as: 64514
---
apiVersion: cnf.namla.com/v1alpha1
kind: CloudNativeNetworkLinuxRoute
metadata:
  name: cnf-default-route-cnf-wan-internet-1-edge4
  namespace: namla-system
spec:
  nodename: edge4
  cnf: cnf-wan-internet-1-edge4
  config:
    scope: GLOBAL
    dst_network: 0.0.0.0/0
    gw_addr: 192.168.30.1 # --> 118
    metric: 0