apiVersion: cnf.namla.com/v1alpha1
kind: CloudNativeNetworkFunction
metadata:
  name: cnf-wan-internet-1-edge-4
  namespace: namla-system
spec:
  address: 172.20.3.13/32
  ifname: ens5
  nodename: edge-amine4
  nvni-name: nvni-1
  type: WAN
  control-plane:
    bgp-as: 64514
---
apiVersion: cnf.namla.com/v1alpha1
kind: CloudNativeNetworkLinuxRoute
metadata:
  name: cnf-default-route-cnf-wan-internet-1-edge-amine4
  namespace: namla-system
spec:
  nodename: edge-amine4
  cnf: cnf-wan-internet-1-edge-amine4
  config:
    scope: GLOBAL
    dst_network: 0.0.0.0/0
    gw_addr: 172.20.3.1  # ---> 207
    metric: 0