apiVersion: cnf.namla.com/v1alpha1
kind: CloudNativeNetworkFunction
metadata:
  name: cnf-wan-internet-1-edge-amine2
  namespace: namla-system
spec:
  address: 172.20.1.17/24
  ifname: ens5
  nodename: edge-amine2
  transport_network: internet
  nvni-name: nvni-1
  type: WAN
  control-plane:
    bgp-as: 64514
---
apiVersion: cnf.namla.com/v1alpha1
kind: CloudNativeNetworkLinuxRoute
metadata:
  name: cnf-default-route-cnf-wan-internet-1-edge-amine2
  namespace: namla-system
spec:
  nodename: edge-amine2
  cnf: cnf-wan-internet-1-edge-amine2
  config:
    scope: GLOBAL
    dst_network: 0.0.0.0/0
    gw_addr: 172.20.1.1 # --> 118
    metric: 0